server:
  port: 8083 # порт на котором висит Publisher

spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop # drop удобен для теста проекта.
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: root
    password: admin
    driverClassName: org.h2.Driver
subscriber:
  url: "http://172.119.0.3:8080/api/subscriber/v1/receiveMessage"



