spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop # drop удобен для теста проекта.
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb # serverTimezone для решения ошибки MySql
    username: root
    password: admin
    driverClassName: org.h2.Driver

